### ISSUE TITLE
eHx Demo QA and documentation

### ISSUE THREAD

**Issue by mojitoj** [sdhealthconnect/leap-demos#10]
- Configure and run the demo 
- Complete the README documentation on how to configure and run the demo

**Comment by sgroh** [comment]
@ddecouteau, editing this comment since seems that CI is fixed now.
Should we coordinate something to fix CI or is not necessary?

**Comment by mojitoj** [comment]
@sgroh Does the latest PR close this or is there more left?

**Comment by sgroh** [comment]
> @sgroh Does the latest PR close this or is there more left?

I' ve demo it on my laptop, but if the configuration I've provided works fine on other machines, we can close this. 
We have a second round with @ddecouteau today to finish this.

**Comment by mojitoj** [comment]
I think if everything is containerized we don't have to worry about one machine vs. another.

**Comment by ddecouteau** [comment]
I've checked out from scratch and run via Mock Service, much cleaner thank you, @sgroh and @mojitoj  this issue can be closed.
